name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - '**'

  pull_request:
    types: [closed]
    branches:
      - main
      - dev
      - 54-feature-cicd-파이프라인-구축

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SSM_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SSM_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Extract RDS hostname from DB_URL
        run: |
          # DB_URL에서 호스트명 추출 (jdbc:mysql://hostname:port/dbname 형식 가정)
          RDS_HOST=$(echo ${{ secrets.DB_URL }} | sed -E 's/jdbc:mysql:\/\/([^:\/]+).*/\1/')
          echo "RDS_HOST=$RDS_HOST" >> $GITHUB_ENV
          echo "RDS 호스트명이 추출되었습니다: $RDS_HOST"

      - name: Start SSM Session for RDS Port Forwarding
        run: |
          # 백그라운드에서 SSM 세션 실행하여 RDS에 포트포워딩
          nohup aws ssm start-session \
            --target ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name AWS-StartPortForwardingSessionToRemoteHost \
            --parameters '{"host":["${{ env.RDS_HOST }}"],"portNumber":["3306"],"localPortNumber":["3306"]}' \
            > ssm_session.log 2>&1 &
          # SSM 세션이 설정될 때까지 잠시 대기
          sleep 20
          echo "SSM 포트 포워딩 세션이 시작되었습니다."

      - name: Verify SSM Session Connection
        run: |
          echo "========== SSM 세션 로그 확인 ==========="
          if [ -f ssm_session.log ]; then
            cat ssm_session.log
          else
            echo "ssm_session.log 파일이 없습니다."
          fi
          
          echo "========== 로컬 포트 확인 ==========="
          netstat -tuln | grep 3306 || echo "포트 3306이 리스닝 상태가 아닙니다."
          
          echo "========== 연결 테스트 ==========="
          nc -z localhost 3306
          if [ $? -eq 0 ]; then
            echo "localhost:3306 연결 성공"
          else
            echo "localhost:3306 연결 실패"
          fi
          echo "====================================="

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew clean build
        env:
          # jOOQ 생성 시 필요한 데이터베이스 연결 정보
          DB_URL: "jdbc:mysql://localhost:3306/${{ secrets.DB_NAME }}"
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Terminate SSM Session
        if: always()
        run: |
          # SSM 세션 종료 (빌드 성공/실패 여부와 관계없이 항상 실행)
          SESSION_ID=$(grep -oP 'Starting session with SessionId: \K[a-zA-Z0-9-]+' ssm_session.log || echo "")
          if [ -n "$SESSION_ID" ]; then
            aws ssm terminate-session --session-id $SESSION_ID
            echo "SSM 세션이 종료되었습니다: $SESSION_ID"
          else
            echo "실행 중인 SSM 세션을 찾을 수 없습니다."
          fi

  deploy:
    if: github.event.pull_request.merged == true
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SSM_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SSM_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Extract RDS hostname from DB_URL
        run: |
          # DB_URL에서 호스트명 추출 (jdbc:mysql://hostname:port/dbname 형식 가정)
          RDS_HOST=$(echo ${{ secrets.DB_URL }} | sed -E 's/jdbc:mysql:\/\/([^:\/]+).*/\1/')
          echo "RDS_HOST=$RDS_HOST" >> $GITHUB_ENV
          echo "RDS 호스트명이 추출되었습니다: $RDS_HOST"

      - name: Start SSM Session for RDS Port Forwarding
        run: |
          # 백그라운드에서 SSM 세션 실행하여 RDS에 포트포워딩
          nohup aws ssm start-session \
            --target ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name AWS-StartPortForwardingSessionToRemoteHost \
            --parameters '{"host":["${{ env.RDS_HOST }}"],"portNumber":["3306"],"localPortNumber":["3306"]}' \
            > ssm_session.log 2>&1 &
          # SSM 세션이 설정될 때까지 잠시 대기
          sleep 20
          echo "SSM 포트 포워딩 세션이 시작되었습니다."

      - name: Verify SSM Session Connection
        run: |
          echo "========== SSM 세션 로그 확인 ==========="
          if [ -f ssm_session.log ]; then
            cat ssm_session.log
          else
            echo "ssm_session.log 파일이 없습니다."
          fi
          
          echo "========== 로컬 포트 확인 ==========="
          netstat -tuln | grep 3306 || echo "포트 3306이 리스닝 상태가 아닙니다."
          
          echo "========== 연결 테스트 ==========="
          nc -z localhost 3306
          if [ $? -eq 0 ]; then
            echo "localhost:3306 연결 성공"
          else
            echo "localhost:3306 연결 실패"
          fi
          echo "====================================="

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          # jOOQ 생성 시 필요한 데이터베이스 연결 정보
          DB_URL: "jdbc:mysql://localhost:3306/${{ secrets.DB_NAME }}"
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Terminate SSM Session
        if: always()
        run: |
          # SSM 세션 종료 (빌드 성공/실패 여부와 관계없이 항상 실행)
          SESSION_ID=$(grep -oP 'Starting session with SessionId: \K[a-zA-Z0-9-]+' ssm_session.log || echo "")
          if [ -n "$SESSION_ID" ]; then
            aws ssm terminate-session --session-id $SESSION_ID
            echo "SSM 세션이 종료되었습니다: $SESSION_ID"
          else
            echo "실행 중인 SSM 세션을 찾을 수 없습니다."
          fi

      - name: Find Executable JAR
        id: find-jar
        run: |
          JAR_FILE=$(find build/libs -name "*.jar" -not -name "*plain.jar" | head -n 1)
          echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
          echo "Found executable JAR: $JAR_FILE"

      - name: Transfer JAR file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PEM_KEY }}
          source: ${{ steps.find-jar.outputs.jar_file }}
          target: "~/app"
          strip_components: 2

      - name: Deploy application to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
            # 앱 디렉토리 확인
            mkdir -p ~/app
            cd ~/app
            
            # 8080 포트를 사용하는 프로세스 종료
            PID=$(lsof -t -i:8080 || echo "")
            
            if [ -n "$PID" ]; then
              echo "Stopping application running on port 8080 with PID: $PID"
              kill $PID
            
              # 최대 20초까지 기다리며 프로세스가 종료되었는지 확인
              COUNTER=0
              while [ $COUNTER -lt 20 ] && ps -p $PID > /dev/null; do
                echo "Waiting for application to stop... ($COUNTER/20)"
                sleep 1
                COUNTER=$((COUNTER+1))
              done
            
              # 20초 후에도 종료되지 않으면 강제 종료
              if ps -p $PID > /dev/null; then
                echo "Force stopping application..."
                kill -9 $PID
                sleep 2
              fi
            
              # 포트가 정상적으로 해제되었는지 확인
              if lsof -t -i:8080 > /dev/null; then
                echo "Warning: Port 8080 is still in use!"
              else
                echo "Port 8080 is now free"
              fi
            else
              echo "No application running on port 8080"
            fi
            
            # 새 JAR 파일 찾기 (plain.jar 제외)
            JAR_FILE=$(find . -name "*.jar" -not -name "*plain.jar" | sort -t '.' -k2,2 -r | head -n 1)
            echo "Starting application with JAR file: $JAR_FILE"
            
            PROFILE="prod"

            echo "Using profile: $PROFILE"
            
            # 애플리케이션 실행 (환경 변수 설정)
            nohup java -Xmx512m -Xms256m -jar $JAR_FILE \
              --spring.profiles.active=$PROFILE \
              --server.port=8080 \
              --DB_URL=${{ secrets.DB_URL }} \
              --DB_NAME=${{ secrets.DB_NAME }} \
              --DB_USERNAME=${{ secrets.DB_USERNAME }} \
              --DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              --SMTP_HOST=${{ secrets.SMTP_HOST }} \
              --SMTP_PORT=${{ secrets.SMTP_PORT }} \
              --SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} \
              --SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
              --JWT_SECRET=${{ secrets.JWT_SECRET }} \
              > app.log 2>&1 &
            
            # PID 파일 생성 (향후 종료를 위해)
            echo $! > app.pid
            
            # 애플리케이션이 시작되었는지 확인
            sleep 10
            if ps -p $(cat app.pid) > /dev/null; then
              echo "Application started successfully with PID: $(cat app.pid)"
            
              # 포트 열렸는지 확인
              if lsof -t -i:8080 > /dev/null; then
                echo "Application is listening on port 8080"
              else
                echo "Warning: Application started but not listening on port 8080!"
                echo "Checking logs for errors:"
                tail -n 50 app.log
                exit 1
              fi
            else
              echo "Application failed to start. Check app.log for details."
              tail -n 50 app.log
              exit 1
            fi